# Generated by Django 3.1.6 on 2021-03-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_deadlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.FileField(upload_to='static/staticfiles/'),
        ),
    ]
