# Generated by Django 3.1.6 on 2021-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_deadlines', '0004_course_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='school_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='school_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
